export const MAIL_ALERT_REQUEST = "MAIL_ALERT_REQUEST";
export const MAIL_ALERT_SUCCESS = "MAIL_ALERT_SUCCESS";
export const MAIL_ALERT_FAILURE = "MAIL_ALERT_FAILURE";

export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAILURE = "GET_DETAILS_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const UPLOAD_PROJECT_REQUEST = "UPLOAD_PROJECT_REQUEST";
export const UPLOAD_PROJECT_SUCCESS = "UPLOAD_PROJECT_SUCCESS";
export const UPLOAD_PROJECT_FAILURE = "UPLOAD_PROJECT_FAILURE";
